# Generated by Django 4.1.3 on 2022-12-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kit',
            new_name='Item',
        ),
    ]
