# Generated by Django 4.1.4 on 2022-12-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_rename_kit_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='disp',
            field=models.BooleanField(default=True),
        ),
    ]
