# Generated by Django 4.1.4 on 2022-12-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kit',
            new_name='Inicio',
        ),
    ]
