# Generated by Django 4.1.4 on 2022-12-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
